# Configuración de Netlify para Casa Profética
# Este archivo configura el deployment de tu sitio web en Netlify

[build]
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio que contiene los archivos estáticos del build
  publish = "dist"

# Redirecciones para SPA (Single Page Application)
# Esto asegura que React Router funcione correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
